// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package verifier

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SetConfig is the `setConfig` instruction.
type SetConfig struct {
	Signers *[][20]uint8
	F       *uint8

	// [0] = [WRITE] verifierAccount
	//
	// [1] = [SIGNER] owner
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSetConfigInstructionBuilder creates a new `SetConfig` instruction builder.
func NewSetConfigInstructionBuilder() *SetConfig {
	nd := &SetConfig{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetSigners sets the "signers" parameter.
func (inst *SetConfig) SetSigners(signers [][20]uint8) *SetConfig {
	inst.Signers = &signers
	return inst
}

// SetF sets the "f" parameter.
func (inst *SetConfig) SetF(f uint8) *SetConfig {
	inst.F = &f
	return inst
}

// SetVerifierAccountAccount sets the "verifierAccount" account.
func (inst *SetConfig) SetVerifierAccountAccount(verifierAccount ag_solanago.PublicKey) *SetConfig {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(verifierAccount).WRITE()
	return inst
}

// GetVerifierAccountAccount gets the "verifierAccount" account.
func (inst *SetConfig) GetVerifierAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetOwnerAccount sets the "owner" account.
func (inst *SetConfig) SetOwnerAccount(owner ag_solanago.PublicKey) *SetConfig {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(owner).SIGNER()
	return inst
}

// GetOwnerAccount gets the "owner" account.
func (inst *SetConfig) GetOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst SetConfig) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SetConfig,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SetConfig) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SetConfig) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Signers == nil {
			return errors.New("Signers parameter is not set")
		}
		if inst.F == nil {
			return errors.New("F parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.VerifierAccount is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Owner is not set")
		}
	}
	return nil
}

func (inst *SetConfig) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SetConfig")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Signers", *inst.Signers))
						paramsBranch.Child(ag_format.Param("      F", *inst.F))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("verifier", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("   owner", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj SetConfig) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Signers` param:
	err = encoder.Encode(obj.Signers)
	if err != nil {
		return err
	}
	// Serialize `F` param:
	err = encoder.Encode(obj.F)
	if err != nil {
		return err
	}
	return nil
}
func (obj *SetConfig) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Signers`:
	err = decoder.Decode(&obj.Signers)
	if err != nil {
		return err
	}
	// Deserialize `F`:
	err = decoder.Decode(&obj.F)
	if err != nil {
		return err
	}
	return nil
}

// NewSetConfigInstruction declares a new SetConfig instruction with the provided parameters and accounts.
func NewSetConfigInstruction(
	// Parameters:
	signers [][20]uint8,
	f uint8,
	// Accounts:
	verifierAccount ag_solanago.PublicKey,
	owner ag_solanago.PublicKey) *SetConfig {
	return NewSetConfigInstructionBuilder().
		SetSigners(signers).
		SetF(f).
		SetVerifierAccountAccount(verifierAccount).
		SetOwnerAccount(owner)
}
